version: "3.3"
services:
  fanManager:
    image: ghcr.io/danielv123/servermanager:latest
    restart: unless-stopped
    ports:
      - 8085:8080 # external:internal
    volumes:
      - /home/jwowk/docker/serverManager:/usr/src/app/data
    # labels:
    #   homepage.group: "T630"
    #   homepage.name: "fanManager"
    #   homepage.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/reactjs.svg"
    #   homepage.href: "http://192.168.0.160:8085/"
    #   homepage.description: "fanManager - Dell Server Fan Controller "
  # ouroboros: # For autoupdate, feel free to remove
  #   container_name: ouroboros
  #   hostname: ouroboros
  #   image: pyouroboros/ouroboros
  #   environment:
  #     - CLEANUP=true
  #     - INTERVAL=86400
  #     - LOG_LEVEL=info
  #     - SELF_UPDATE=true
  #     - IGNORE=mongo influxdb postgres mariadb
  #     - TZ=America/Chicago
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
